name: 'Setup CMake'
description: 'Downloads, verifies (if hash provided), extracts, caches, and optionally adds a specific version of CMake to the PATH.' # Updated description

inputs:
  cmake-version:
    description: 'The CMake version to download (e.g., 3.28.3) or "latest".'
    required: true
  cmake-hash:
    description: >
      Optional. The expected SHA512 hash of the CMake archive for the target platform.
      If provided, the download integrity will be verified.
      If omitted, hash verification is skipped, and Terrapin tool (if available) will not be used.
      Omitting the hash increases security risks (supply chain attacks).
    required: false
  terrapin-tool-path:
    description: 'Path to the TerrapinRetrievalTool.exe executable (if used).'
    required: false
    default: 'C:/local/Terrapin/TerrapinRetrievalTool.exe'
  disable-terrapin:
    description: 'Set to true to bypass Terrapin and download directly.'
    required: false
    default: 'false'
  add-to-path:
    description: 'If true, add the CMake bin directory to the PATH environment variable.'
    required: false
    default: 'true'

outputs:
  cmake-root:
    description: 'The root directory path of the cached CMake installation.'
  cmake-path:
    description: > 
      The path to the directory containing the CMake executables (e.g., /path/to/cmake/bin).
      This path is added to the system PATH only if `add-to-path` is true.

runs:
  using: 'node20'
  main: 'dist/index.js'